ARG IMAGE_TAG="7.4-fpm"

FROM zhiqiangwang/php:${IMAGE_TAG}-composer

RUN apt-get update && apt-get install -y nginx supervisor \
    && apt clean && rm -rf /var/lib/apt/lists/*

ADD ./conf/nginx/default /etc/nginx/sites-enabled/default
ADD ./conf/supervisor/nginx-php.conf /etc/supervisor/conf.d

RUN mkdir -p /var/log/supervisor

RUN echo "<?php phpinfo(); ?>" >> /var/www/html/index.php

EXPOSE 80 443 9000

CMD ["supervisord", "-u", "root", "-c", "/etc/supervisor/supervisord.conf"]